---
kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: publish-image
  image: plugins/docker
  settings:
    force_tag: true
    password:
      from_secret: registry-password
    registry:
      from_secret: registry-server
    repo:
      from_secret: registry-repo
    tags: ${DRONE_TAG##v}
    username:
      from_secret: registry-user
  when:
    event:
    - tag
    ref:
    - refs/heads/master
    - refs/tags/*

trigger:
  event:
  - tag
  ref:
  - refs/heads/master
  - refs/tags/*

---
kind: signature
hmac: 9ac7c46c3c5eb0544e29db7c1b6f4df4b93858fdb7d0b3bc41fe9807052c0000

...
