apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-deployer
  namespace: {{adjust-namespace}}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-deployer
  namespace: {{adjust-namespace}}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-deployer
  namespace: {{adjust-namespace}}
subjects:
- kind: ServiceAccount
  name: ci-deployer
  namespace: {{adjust-namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ci-deployer
